#%RAML 1.0 Trait

queryParameters:
  limit:
    description: The limit to be used to limit the number of items in the response.
    type: number
    required: false
  offset:
    description: The offset where the item list in the response will start.
    type: string   
    required: false