  post:
    description: Authorize user and create a new token.
    securedBy: [ null ]
    body:
      application/json:
        type: Auth
    responses:
      201:
        body:
          application/json:
            type: AuthResponse
  /{token}:
    get:
      description: Get all extracted data of given token.
      is: [ hasResponseItem: { typeName: Session } ]
    delete:
      description: Deletes the given token.        
