  displayName: "[System] Communication Mail Accounts"
  description: !include ../../../descriptions/resources/system/communication/mailaccounts.md
  type: { collection: { typeName: MailAccount } }
  /{mailAccountId}:
    type: { item: { typeName: MailAccount } }
    uriParameters:
      mailAccountId:
        displayName: MailAccountID
        type: integer
