  usage: Use this resourceType to represent a collection of items
  description: A collection of <<resourcePathName|!uppercamelcase>>
  get:
    description: |
      Get all <<resourcePathName|!uppercamelcase>>.
    is: [ hasResponseCollection: { typeName: <<typeName>> }, hasBadRequest, filterable, pageable, sortable ]
  post:
    description: |
      Create a new <<resourcePathName|!uppercamelcase|!singularize>>.
    is: [ hasRequestItem: { typeName: <<typeName>>PostRequest }, hasBadRequest, hasConflict ]
    responses:
      201:
        description: |
          The <<typeName>> has been created successfully.
        body:
          application/json: 
            type: <<typeName>>PostResponse
