  usage: Use this resourceType to represent any single item
  patch:
    is: [ hasRequestItem: { typeName: <<typeName>>PatchRequest }, hasResponseItem: { typeName: <<typeName>>PatchResponse }, hasBadRequest, hasNotFound, hasConflict ]