  usage: Use this resourceType to represent any single item
  description: A single <<typeName>>
  get:
    description: Get a <<typeName>>
    is: [ hasResponseItem: { typeName: <<typeName>> }, hasNotFound, supportingFieldSelection ]
  patch:
    description: Partially update a <<typeName>>
    is: [ hasRequestItem: { typeName: <<typeName>>PatchRequest }, hasResponseItem: { typeName: <<typeName>>PatchResponse }, hasBadRequest, hasNotFound, hasConflict ]
  delete:
    description: Delete a <<typeName>>
    is: [ hasNotFound, hasConflict, hasNoContent ]
