  usage: Use this resourceType to represent any single item
  get:
    is: [ hasResponseItem: { typeName: <<typeName>>Response }, hasNotFound, supportingFieldSelection ]
  patch:
    is: [ hasRequestItem: { typeName: <<typeName>>PatchRequest }, hasResponseItem: { typeName: <<typeName>>PostPatchResponse }, hasBadRequest, hasNotFound, hasConflict ]
  delete:
    is: [ hasNotFound, hasConflict, hasNoContent ]
