  collection: !include ../resourceTypes/collection.raml
  collection-readonly: !include ../resourceTypes/collection-readonly.raml
  item: !include ../resourceTypes/item.raml
  item-readonly: !include ../resourceTypes/item-readonly.raml