  collection: !include ../resourceTypes/collection.raml
  collection-nopatch: !include ../resourceTypes/collection-nopatch.raml
  collection-readonly: !include ../resourceTypes/collection-readonly.raml
  item: !include ../resourceTypes/item.raml
  item-readonly: !include ../resourceTypes/item-readonly.raml
  item-nopatch: !include ../resourceTypes/item-nopatch.raml
  item-nopatch-nodelete: !include ../resourceTypes/item-nopatch-nodelete.raml