# ArticleType
  ArticleType: !include ../types/ArticleType/ArticleType.raml
  ArticleTypeList: !include ../types/ArticleType/ArticleTypeList.raml

# Auth
  AuthRequest: !include ../types/Auth/AuthRequest.raml
  AuthResponse: !include ../types/Auth/AuthResponse.raml

# Error 
  Error: !include ../types/Error/Error.raml

# Lock
  Lock: !include ../types/Lock/Lock.raml
  LockList: !include ../types/Lock/LockList.raml

# Priority 
  Priority: !include ../types/Priority/Priority.raml
  PriorityList: !include ../types/Priority/PriorityList.raml
  PriorityPatchRequest: !include ../types/Priority/PriorityPatchRequest.raml
  PriorityPatchResponse: !include ../types/Priority/PriorityPatchResponse.raml
  PriorityPostRequest: !include ../types/Priority/PriorityPostRequest.raml
  PriorityPostResponse: !include ../types/Priority/PriorityPostResponse.raml
  
# SenderType
  SenderType: !include ../types/SenderType/SenderType.raml
  SenderTypeList: !include ../types/SenderType/SenderTypeList.raml

# Session 
  Session: !include ../types/Session/Session.raml

# StateType
  StateType: !include ../types/StateType/StateType.raml
  StateTypeList: !include ../types/StateType/StateTypeList.raml

# TicketState
  TicketState: !include ../types/TicketState/TicketState.raml
  TicketStateList: !include ../types/TicketState/TicketStateList.raml
  TicketStatePatchRequest: !include ../types/TicketState/TicketStatePatchRequest.raml
  TicketStatePatchResponse: !include ../types/TicketState/TicketStatePatchResponse.raml
  TicketStatePostRequest: !include ../types/TicketState/TicketStatePostRequest.raml
  TicketStatePostResponse: !include ../types/TicketState/TicketStatePostResponse.raml

# TicketType
  TicketType: !include ../types/TicketType/TicketType.raml
  TicketTypeList: !include ../types/TicketType/TicketTypeList.raml
  TicketTypePatchRequest: !include ../types/TicketType/TicketTypePatchRequest.raml
  TicketTypePatchResponse: !include ../types/TicketType/TicketTypePatchResponse.raml
  TicketTypePostRequest: !include ../types/TicketType/TicketTypePostRequest.raml
  TicketTypePostResponse: !include ../types/TicketType/TicketTypePostResponse.raml

# User
  User: !include ../types/User/User.raml
  UserList: !include ../types/User/UserList.raml
  UserPatchRequest: !include ../types/User/UserPatchRequest.raml
  UserPatchResponse: !include ../types/User/UserPatchResponse.raml
  UserPostRequest: !include ../types/User/UserPostRequest.raml
  UserPostResponse: !include ../types/User/UserPostResponse.raml

# Valid
  Valid: !include ../types/Valid/Valid.raml
  ValidList: !include ../types/Valid/ValidList.raml
