# Channel
  Channel: !include ../types/Channel/Channel.raml
  ChannelList: !include ../types/Channel/ChannelList.raml

# Auth
  AuthRequest: !include ../types/Auth/AuthRequest.raml
  AuthResponse: !include ../types/Auth/AuthResponse.raml

# ConfigItemClass
  ConfigItemClass: !include ../types/ConfigItemClass/ConfigItemClass.raml
  ConfigItemClassList: !include ../types/ConfigItemClass/ConfigItemClassList.raml
  ConfigItemClassPostRequest: !include ../types/ConfigItemClass/ConfigItemClassPostRequest.raml
  ConfigItemClassPatchRequest: !include ../types/ConfigItemClass/ConfigItemClassPatchRequest.raml
  ConfigItemClassPostPatchResponse: !include ../types/ConfigItemClass/ConfigItemClassPostPatchResponse.raml
  ConfigItemClassDefinition: !include ../types/ConfigItemClassDefinition/ConfigItemClassDefinition.raml
  ConfigItemClassDefinitionList: !include ../types/ConfigItemClassDefinition/ConfigItemClassDefinitionList.raml
  ConfigItemClassDefinitionPostRequest: !include ../types/ConfigItemClassDefinition/ConfigItemClassDefinitionPostRequest.raml
  ConfigItemClassDefinitionPostResponse: !include ../types/ConfigItemClassDefinition/ConfigItemClassDefinitionPostResponse.raml
  ConfigItem: !include ../types/ConfigItem/ConfigItem.raml
  ConfigItemList: !include ../types/ConfigItem/ConfigItemList.raml
  ConfigItemPostRequest: !include ../types/ConfigItem/ConfigItemPostRequest.raml
  ConfigItemPatchRequest: !include ../types/ConfigItem/ConfigItemPatchRequest.raml
  ConfigItemPostPatchResponse: !include ../types/ConfigItem/ConfigItemPostPatchResponse.raml
  ConfigItemAttachment: !include ../types/ConfigItemAttachment/ConfigItemAttachment.raml
  ConfigItemHistory: !include ../types/ConfigItemHistory/ConfigItemHistory.raml
  ConfigItemHistoryList: !include ../types/ConfigItemHistory/ConfigItemHistoryList.raml
  ConfigItemImage: !include ../types/ConfigItemImage/ConfigItemImage.raml
  ConfigItemImageList: !include ../types/ConfigItemImage/ConfigItemImageList.raml
  ConfigItemImagePostRequest: !include ../types/ConfigItemImage/ConfigItemImagePostRequest.raml
  ConfigItemImagePostResponse: !include ../types/ConfigItemImage/ConfigItemImagePostResponse.raml
  ConfigItemVersion: !include ../types/ConfigItemVersion/ConfigItemVersion.raml
  ConfigItemVersionList: !include ../types/ConfigItemVersion/ConfigItemVersionList.raml
  ConfigItemVersionPostRequest: !include ../types/ConfigItemVersion/ConfigItemVersionPostRequest.raml
  ConfigItemVersionPostResponse: !include ../types/ConfigItemVersion/ConfigItemVersionPostResponse.raml

# ClientRegistration
  ClientRegistration: !include ../types/ClientRegistration/ClientRegistration.raml
  ClientRegistrationList: !include ../types/ClientRegistration/ClientRegistrationList.raml
  ClientRegistrationPostRequest: !include ../types/ClientRegistration/ClientRegistrationPostRequest.raml
  ClientRegistrationPostResponse: !include ../types/ClientRegistration/ClientRegistrationPostResponse.raml

# Error 
  Error: !include ../types/Error/Error.raml

# Lock
  Lock: !include ../types/Lock/Lock.raml
  LockList: !include ../types/Lock/LockList.raml

# Priority 
  Priority: !include ../types/Priority/Priority.raml
  PriorityList: !include ../types/Priority/PriorityList.raml
  PriorityPostRequest: !include ../types/Priority/PriorityPostRequest.raml
  PriorityPatchRequest: !include ../types/Priority/PriorityPatchRequest.raml
  PriorityPostPatchResponse: !include ../types/Priority/PriorityPostPatchResponse.raml
  
# SenderType
  SenderType: !include ../types/SenderType/SenderType.raml
  SenderTypeList: !include ../types/SenderType/SenderTypeList.raml

# Session 
  Session: !include ../types/Session/Session.raml

# StateType
  StateType: !include ../types/StateType/StateType.raml
  StateTypeList: !include ../types/StateType/StateTypeList.raml

# TicketState
  TicketState: !include ../types/TicketState/TicketState.raml
  TicketStateList: !include ../types/TicketState/TicketStateList.raml
  TicketStatePostRequest: !include ../types/TicketState/TicketStatePostRequest.raml
  TicketStatePatchRequest: !include ../types/TicketState/TicketStatePatchRequest.raml
  TicketStatePostPatchResponse: !include ../types/TicketState/TicketStatePostPatchResponse.raml

# TicketType
  TicketType: !include ../types/TicketType/TicketType.raml
  TicketTypeList: !include ../types/TicketType/TicketTypeList.raml
  TicketTypePostRequest: !include ../types/TicketType/TicketTypePostRequest.raml
  TicketTypePatchRequest: !include ../types/TicketType/TicketTypePatchRequest.raml
  TicketTypePostPatchResponse: !include ../types/TicketType/TicketTypePostPatchResponse.raml

# Translation
  Translation: !include ../types/Translation/Translation.raml
  TranslationList: !include ../types/Translation/TranslationList.raml
  TranslationPostRequest: !include ../types/Translation/TranslationPostRequest.raml
  TranslationPatchRequest: !include ../types/Translation/TranslationPatchRequest.raml
  TranslationPostPatchResponse: !include ../types/Translation/TranslationPostPatchResponse.raml
  TranslationLanguage: !include ../types/Translation/TranslationLanguage.raml
  TranslationLanguageList: !include ../types/Translation/TranslationLanguageList.raml
  TranslationLanguagePostRequest: !include ../types/Translation/TranslationLanguagePostRequest.raml
  TranslationLanguagePatchRequest: !include ../types/Translation/TranslationLanguagePatchRequest.raml
  TranslationLanguagePostPatchResponse: !include ../types/Translation/TranslationLanguagePostPatchResponse.raml

# User
  User: !include ../types/User/User.raml
  UserList: !include ../types/User/UserList.raml
  UserPostRequest: !include ../types/User/UserPostRequest.raml
  UserPatchRequest: !include ../types/User/UserPatchRequest.raml
  UserPostPatchResponse: !include ../types/User/UserPostPatchResponse.raml
  UserPreference: !include ../types/User/UserPreference.raml
  UserPreferenceList: !include ../types/User/UserPreferenceList.raml
  UserPreferencePostRequest: !include ../types/User/UserPreferencePostRequest.raml
  UserPreferencePatchRequest: !include ../types/User/UserPreferencePatchRequest.raml
  UserPreferencePostPatchResponse: !include ../types/User/UserPreferencePostPatchResponse.raml

# Valid
  Valid: !include ../types/Valid/Valid.raml
  ValidList: !include ../types/Valid/ValidList.raml
