  displayName: Communication Channels
  description: !include ../descriptions/resources/channels.md
  type: { collection-readonly: { typeName: Channel } }
  /{channelId}:
    type: { item-readonly: { typeName: Channel } }
    uriParameters:
      channelId:
        displayName: ChannelID
        type: integer
