  displayName: Client Registrations
  description: !include ../descriptions/resources/clientregistrations.md
  type: { collection: { typeName: ClientRegistration } }
  /{clientId}:
    type: { item-nopatch: { typeName: ClientRegistration } }
    uriParameters:
      clientId:
        displayName: ClientID
        type: string
