  displayName: CMDB
  description: !include ../descriptions/resources/cmdb.md
  /classes:
    description: !include ../descriptions/resources/cmdb/classes.md
    type: { collection-nopatch: { typeName: ConfigItemClass } }
    /{classId}:
      type: { item: { typeName: ConfigItemClass } }
      uriParameters:
        classId:
          displayName: ClassID
          type: integer
      /definitions:
        description: !include ../descriptions/resources/cmdb/classes/definitions.md
        type: { collection: { typeName: ConfigItemClassDefinition } }
        /{definitionId}:
          type: { item-nopatch: { typeName: ConfigItemClassDefinition } }
          uriParameters:
            definitionId:
              displayName: DefinitionID
              type: integer
  /configitems:
    description: !include ../descriptions/resources/cmdb/configitems.md
    type: { collection: { typeName: ConfigItem } }
    /{configItemId}:
      type: { item: { typeName: ConfigItem } }
      uriParameters:
        configItemId:
          displayName: ConfigItemID
          type: integer
      /history:
        description: !include ../descriptions/resources/cmdb/configitems/history.md
        type: { collection-readonly: { typeName: ConfigItemHistory } }
        /{historyId}:
          type: { item-readonly: { typeName: ConfigItemHistory } }
          uriParameters:
            historyId:
              displayName: HistoryID
              type: integer
      /images:
        description: !include ../descriptions/resources/cmdb/configitems/images.md
        type: { collection-nopatch: { typeName: ConfigItemImage } }
        /{imageId}:
          type: { item-nopatch: { typeName: ConfigItemImage } }
          uriParameters:
            imageId:
              displayName: ImageID
              type: integer
      /versions:
        description: !include ../descriptions/resources/cmdb/configitems/versions.md
        type: { collection-nopatch: { typeName: ConfigItemVersion } }
        /{versionId}:
          type: { item-readonly: { typeName: ConfigItemVersion } }
          uriParameters:
            versionId:
              displayName: VersionID
              type: integer
    /attachments/{attachmentId}:
        description: !include ../descriptions/resources/cmdb/configitems/attachments.md
        type: { item-readonly: { typeName: ConfigItemAttachment } }
        uriParameters:
          attachmentId:
            displayName: AttachmentID
            type: integer
