  displayName: FAQ
  description: !include ../descriptions/resources/faq.md
  /articles:
    description: !include ../descriptions/resources/faq/articles.md
    /keywords:
      description: !include ../descriptions/resources/faq/articles/keywords.md
      type: { collection-readonly: { typeName: FAQKeyword } }
