  displayName: i18n
  description: !include ../descriptions/resources/i18n.md
  /translations:
    description: !include ../descriptions/resources/i18n/translations.md
    type: { collection-readonly: { typeName: Translation } }
