  displayName: Object Icons
  description: !include ../descriptions/resources/objecticons.md
  type: { collection: { typeName: ObjectIcon } }
  /{objectIconId}:
    type: { item: { typeName: ObjectIcon } }
    uriParameters:
      objectIconId:
        displayName: ObjectIconID
        type: integer
