  displayName: ObjectSearch
  description: !include ../descriptions/resources/objectsearch.md
  type: { collection: { typeName: ObjectSearch } }
  /{objecttype}:
    uriParameters:
      objecttype:
        displayName: ObjectType
        type: string
