  displayName: ObjectSearch
  description: !include ../descriptions/resources/objectsearch.md
  type: { collection-readonly: { typeName: ObjectSearchSupportedAttributes } }
  /{objecttype}:
    type: { item-readonly: { typeName: ObjectSearchSupportedAttributes } }
    uriParameters:
      objecttype:
        displayName: ObjectType
        type: string
