  displayName: Roles
  description: !include ../descriptions/resources/roles.md
  type: { collection: { typeName: Role } }
  /{roleId}:
    type: { item: { typeName: Role } }
    uriParameters:
      roleId:
        displayName: RoleID
        type: integer
    /userids:
      description: !include ../descriptions/resources/roles/userids.md
      type: { collection-nopatch: { typeName: RoleUserID } }
      /{userId}:
        type: { item-deleteonly: { typeName: RoleUserID } }
        uriParameters:
          userId:
            displayName: UserID
            type: number