  displayName: Sender Types
  description: !include ../descriptions/resources/sendertypes.md
  type: { collection-readonly: { typeName: SenderType } }
  /{senderTypeId}:
    type: { item-readonly: { typeName: SenderType } }
    uriParameters:
      senderTypeId:
        displayName: SenderTypeID
        type: integer
