  displayName: Services
  description: !include ../descriptions/resources/services.md
  type: { collection: { typeName: Service } }
  /{serviceId}:
    type: { item: { typeName: Service } }
    uriParameters:
      serviceId:
        displayName: ServiceID
        type: integer
