  displayName: Current Session
  description: !include ../descriptions/resources/session.md
  type: [ item-nopatch: { typeName: Session } ]
  /user:
    displayName: Current User
    description: !include ../descriptions/resources/session/user.md
    type: [ item-nodelete: { typeName: User } ]
    /preferences:
      type: { collection: { typeName: UserPreference } }  
      /{preferenceId}:
        type: { item: { typeName: UserPreference } }
        uriParameters:
          preferenceId:
            displayName: PeferenceID
            type: string
