  displayName: Sessions
  description: !include ../descriptions/resources/sessions.md
  post:
    description: Authorize user and create a new token.
    securedBy: [ null ]
    body:
      application/json:
        type: AuthRequest
    responses:
      201:
        body:
          application/json:
            schema: |
              { 
                "$schema": "http://json-schema.org/schema",
                "type": "object",
                "description": "The auth response.",
                "properties": {
                  "Token": { "type": "string" }
                }
              }
            example: |
              {
                "Token": "eyJhbGciOiJIUzI1NiJ9.eyJEZXNjcmlwdGlvbiI6IiIsIlVzZXJJRCI6IjEiLCJVc2VyVHlwZSI6IkFnZW50IiwiQWxsb3dlZE9wZXJhdGlvbnMiOltdLCJJZ25vcmVNYXhJZGxlVGltZSI6MCwiRGVuaWVkT3BlcmF0aW9ucyI6W10sIlJlbW90ZUlQIjoiOjpmZmZmOjE3Mi4xNy4wLjEiLCJUb2tlblR5cGUiOiJOb3JtYWwiLCJDcmVhdGVUaW1lVW5peCI6MTUzNTQ1NjA5NSwiVmFsaWRVbnRpbFRpbWVVbml4IjoxNTM1NTEzNjk1fQ.Ny0LWwELBS7c2K-784_9SpPBEz_HsgJ4s2xQTMSjCso"
              }
  /{token}:
    uriParameters:
      token:
        displayName: Token
        type: string  
    get:
      description: Get all extracted data of given token.
      is: [ hasResponseItem: { typeName: Session } ]
    delete:
      description: Deletes the given token.        
