  displayName: System Addresses
  description: !include ../descriptions/resources/systemaddresses.md
  type: { collection: { typeName: SystemAddress } }
  /{systemAddressId}:
    type: { item: { typeName: SystemAddress } }
    uriParameters:
      systemAddressId:
        displayName: SystemAddressID
        type: integer
