  displayName: Text Modules
  description: !include ../descriptions/resources/textmodules.md
  type: { collection: { typeName: TextModule } }
  /categories:
    description: !include ../descriptions/resources/textmodules/categories.md
    type: { collection-readonly: { typeName: TextModuleCategory } } 
  /{textModuleId}:
    type: { item: { typeName: TextModule } }
    uriParameters:
      textModuleId:
        displayName: TextModuleID
        type: integer
