  displayName: Ticket Locks
  description: !include ../descriptions/resources/ticketlocks.md
  type: { collection-readonly: { typeName: Lock } }
  /{lockId}:
    type: { item-readonly: { typeName: Lock } }
    uriParameters:
      lockId:
        displayName: LockID
        type: integer
