  displayName: Ticket States
  description: !include ../descriptions/resources/ticketstates.md
  type: { collection: { typeName: TicketState } }
  /{stateId}:
    type: { item: { typeName: TicketState } }
    uriParameters:
      stateId:
        displayName: TicketStateID
        type: integer
