  displayName: Current User
  description: !include ../descriptions/resources/user.md
  type: [ item-readonly: { typeName: User } ]
  /preferences:
    type: { collection-readonly: { typeName: UserPreference } }