  displayName: VirtualFS
  description: !include ../descriptions/resources/virtualfs.md
  /{token}:
    type: { item-readonly: { typeName: VirtualFS } }
    uriParameters:
      token:
        displayName: Token
        type: string
