  displayName: "[System] OAuth2 - Authorization Code & State"
  description: !include ../../../descriptions/resources/system/oauth2/authcode.md
  type: { collection-postonly: { typeName: OAuth2AuthCode } }
