  displayName: "[System] Config"
  description: !include ../descriptions/resources/system/config.md
  type: { collection-readonly: { typeName: SysConfigOption } }
  /optiontypes:
    description: !include ../descriptions/resources/system/config/optiontypes.md
    type: { collection-readonly: { typeName: SysConfigOptionType } }
  /{option}:
    type: { item-nodelete: { typeName: SysConfigOption } }
    uriParameters:
      option:
        displayName: Option
        type: string
  /definitions:
    description: !include ../descriptions/resources/system/config/definitions.md
    type: { collection-readonly: { typeName: SysConfigOptionDefinition } }
    /{option}:
      type: { item-readonly: { typeName: SysConfigOptionDefinition } }
      uriParameters:
        option:
          displayName: Option
          type: string