  displayName: "[System] General Catalog"
  description: !include ../../descriptions/resources/system/generalcatalog.md
  type: { collection: { typeName: GeneralCatalogItem } }
  /{generalCatalogItemId}:
    type: { item: { typeName: GeneralCatalogItem } }
    uriParameters:
      generalCatalogItemId:
        displayName: GeneralCatalogItemID
        type: integer
  /classes:
    description: !include ../../descriptions/resources/system/generalcatalog/classes.md
    type: { collection-readonly: { typeName: GeneralCatalogClass } }
    /{className}:
      type: { item-patchonly: { typeName: GeneralCatalogClass } }
      uriParameters:
        className:
          displayName: ClassName
          type: string

