  displayName: "[System] Sessions"
  description: !include ../../descriptions/resources/system/sessions.md
  type: { collection-none: { typeName: Sessions } }
  /{token}:
    type: { item-nopatch: { typeName: Session } }
    uriParameters:
      token:
        displayName: Token
        type: string