  displayName: "[System] Valid"
  description: !include ../../descriptions/resources/system/valid.md
  type: { collection-readonly: { typeName: Valid } }
  /{validId}:
    type: { item-readonly: { typeName: Valid } }
    uriParameters:
      validId:
        displayName:ValidID
        type: integer