  hasConflict: !include ../traits/hasConflict.raml
  hasNotFound: !include ../traits/hasNotFound.raml
  hasRequestItem: !include ../traits/hasRequestItem.raml
  hasResponseCollection: !include ../traits/hasResponseCollection.raml
  hasResponseItem: !include ../traits/hasResponseItem.raml
  secured: !include ../traits/secured.raml
  filterable: !include ../traits/filterable.raml
  searchable: !include ../traits/searchable.raml
  sortable: !include ../traits/sortable.raml
  pageable: !include ../traits/pageable.raml
  supportingExpands: !include ../traits/supportingExpands.raml
  supportingIncludes: !include ../traits/supportingIncludes.raml
  supportingFieldSelection: !include ../traits/supportingFieldSelection.raml