  Auth: !include ../types/Auth.raml
  AuthResponse: !include ../types/AuthResponse.raml
  Error: !include ../types/Error.raml
  Session: !include ../types/Session.raml
  User: !include ../types/User.raml
