  displayName: "[System] Ticket Priorities"
  description: !include ../../../descriptions/resources/system/ticket/priorities.md
  type: { collection: { typeName: Priority } }
  /{priorityId}:
    type: { item: { typeName: Priority } }
    uriParameters:
      priorityId:
        displayName: PriorityID
        type: integer
