#%RAML 1.0 DataType

schema: |
  { "$schema": "http://json-schema.org/schema",
    "type": "object",
    "description": "The created web token.",
    "properties": {
      "Token": { "type": "string" }
    }
  }
example: |
  {
    "Token": "eyJhbGciOiJIUzI1NiJ9.eyJEZXNjcmlwdGlvbiI6IiIsIlVzZXJJRCI6IjEiLCJVc2VyVHlwZSI6IkFnZW50IiwiQWxsb3dlZE9wZXJhdGlvbnMiOltdLCJJZ25vcmVNYXhJZGxlVGltZSI6MCwiRGVuaWVkT3BlcmF0aW9ucyI6W10sIlJlbW90ZUlQIjoiOjpmZmZmOjE3Mi4xNy4wLjEiLCJUb2tlblR5cGUiOiJOb3JtYWwiLCJDcmVhdGVUaW1lVW5peCI6MTUzNTQ1NjA5NSwiVmFsaWRVbnRpbFRpbWVVbml4IjoxNTM1NTEzNjk1fQ.Ny0LWwELBS7c2K-784_9SpPBEz_HsgJ4s2xQTMSjCso"
  }
