#%RAML 1.0 DataType

schema: |
  { "$schema": "http://json-schema.org/schema",
    "type": "object",
    "description": "An error object.",
    "properties": {
      "Code": { "type": "string" },
      "Message": { "type": "string" }
    }
  }
example: |
  {
    "Code": "500",
    "Message": "A server error occured!"
  }