#%RAML 1.0 DataType

schema: |
  { "$schema": "http://json-schema.org/schema",
    "type": "object",
    "description": "The user object.",
    "properties": {
      "ChangeBy": { "type": "number" },
      "ChangeTime": { "type": "string" },
      "CreateBy": { "type": "number" },
      "CreateTime": { "type": "string" },
      "UserFirstname": { "type": "string" },
      "UserFullname": { "type": "string" },
      "UserID": { "type": "number" },
      "UserLastname": { "type": "string" },
      "UserLogin": { "type": "string" },
      "UserTitle": { "type": "string" },
      "ValidID": { "type": "number" }
    }
  }
example: |
  { 
    "ChangeBy": 1,
    "ChangeTime": "2018-09-28 09:17:03",
    "CreateBy": 1,
    "CreateTime": "2018-08-28 11:34:55",
    "UserFirstname": "John",
    "UserFullname": "John Doe",
    "UserID": 3,
    "UserLastname": "Doe",
    "UserLogin": "jdoe",
    "UserTitle": "Dr.",
    "ValidID": 1
  }
